name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: NUXT_APP_BASE_URL=/${{ github.event.repository.name }} npm run generate
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} ||AIzaSyDUMBIkRVDVecRKXcb72s0NNUaLcIJNKGQ
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }} || https://gsbvayifmvdojiqobkcz.supabase.co
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }} || eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYnZheWlmbXZkb2ppcW9ia2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODQ3ODYsImV4cCI6MjA1OTA2MDc4Nn0.GoBHALk4Ka4P66oYyymnhiBXlz1OYt0gyiQSsUycvAw
          
      - name: Create .nojekyll file
        run: touch .output/public/.nojekyll
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .output/public
          token: ${{ secrets.GITHUB_TOKEN }}